# Aplicação geral
spring.application.name=marketplace

# Configuração do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mini-marketplace
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080
server.servlet.context-path=/api

# JWT
security.jwt.secret-key=96ce520b52bc2eb358a562d93d4131433b52a73453e6d6b2
security.jwt.expiration=3600000
